spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rental?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      testWhileIdle: false
      validationQuery: SELECT 1
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  servlet:
    multipart:
      location: D:/file
      max-file-size: 100MB


mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.clt.entity